redis:
    pool:
         maxActive: 300
         maxIdle: 100
         maxWait: 1000
    host: localhost
    port: 6379
    password:
    timeout: 2000
    # 服务或应用名
    sysName: admin
    enable: true
    database: 0


spring:
    application:
        name: rabbitmq-hello
    rabbitmq:
            host: 192.168.8.119
            port:  5672
            username: admin
            password: admin